#!/bin/bash

function echo-all {
  local i
  for i in "$@"
  do
    if [ -f "$i" ]
    then
      # exists and is a file
      echo "$i"
    elif [ -d "$i" ]
    then
      # exists and is a directory
      local j
      for j in "$i"/*
      do
        echo-all "$j"
      done
    else
      echo "$i doesn't exist"
    fi
  done
}

echo-all "$@"
