#!/bin/bash

function find-utf-8-text {
  local i
  for i in "$@"
  do
    if [ -f "$i" ]
    then
      # exists and is a file
      encoding=`file --mime-encoding $i`
      if [ "$encoding" == "$i: utf-8" ]
      then
        first_line=`head -n 1 < $i`
        if [ "$first_line" != "-*- coding: utf-8 -*-" ]
        then
          echo "$i"
        fi
      fi
    elif [ -d "$i" ]
    then
      # exists and is a directory
      local j
      for j in `ls $i`
      do
        find-utf-8-text "$i/$j"
      done
    else
      echo "$i doesn't exist"
    fi
  done
}

find-utf-8-text "$@"
