#!/bin/bash

function find-utf-8-text {
  local i
  for i in "$@"
  do
    if [ -f "$i" ]
    then
      # exists and is a file
      encoding=`file --mime-encoding $i`
      if [ "$encoding" == "$i: utf-8" ]
      then
        echo "$i"
      fi
    elif [ -d "$i" ]
    then
      # exists and is a directory
      local j
      for j in "$i"/*
      do
        find-utf-8-text "$j"
      done
    else
      echo "$i doesn't exist"
    fi
  done
}

find-utf-8-text "$@"
